var WAi18n = {
    lang: {
        searchButtonSearchingText: "Searching...",
        selectionTitle: "-- select address --",
        showMoreResultsText: "Show more results...",
        endResultsText: "End of results.",
        resultsPage01: "-- Results Page ",
        resultsPage02: " of ",
        resultsPage03: " --",
        warningTitle: "Warning",
        defaultButtonText: "Find Address",
        warning001: "Please provide a search value.",
        warning002: "There are no results for the value you have entered. Please try again or fill it manually.",
        errorTitle: "Warning",
        errorDefault: "There was a problem with the service. Please enter your address manually.",
        error001: "Error:c001; searchKey missing from configuration.",
        error002: "Error:c002; searchKey is not a valid format. Please use XXXXX-XXXXX-XXXXX-XXXXX where X can be any letter from A-Z or number from 0-9.",
        error003: "Error:c003; functionName missing from configuration.",
        error004: "Error:c004; functionName is not a valid format. Please use only A-Z, 0-9, Hyphens(-) and Underscores(_).",
        error005: "Error:c005; dataset missing from configuration.",
        error006: "Error:c006; dataset must be one of {0}",
        error007: "Error:c007; datasetField must be a string value containing the field id.",
        error008: "Error:c008; datasetField {0} is not a valid field id.",
        error009: "Error:c009; searchField missing from configuration.",
        error010: "Error:c010; searchField must be a string value containing the field id.",
        error011: "Error:c011; searchField {0} is not a valid field id.",
        error012: "Error:c012; searchButton missing from configuration.",
        error013: "Error:c013; searchButton must be a string value containing the field id.",
        error014: "Error:c014; searchButton {0} is not a valid field id.",
        error015: "Error:c015; paging must be a boolean value containing either true or false.",
        error016: "Error:c016; outputMap missing from configuration.",
        error017: "Error:c017; outputMap.fields missing from configuration.",
        error018: "Error:c018; outputMap.fields must be an array.",
        error019: "Error:c019; outputMap.fields must contain at least one mapping object.",
        error020: "Error:c020; outputMap.fields missing id for field {0}.",
        error021: "Error:c021; outputMap.fields field {0} must be a string value containing the field id.",
        error022: "Error:c022; outputMap.fields field {0} {1} is not a valid field id.",
        error023: "Error:c023; outputMap.fields missing dataIndex for field {0}.",
        error024: "Error:c024; outputMap.fields.dataIndex must be a number or an array.",
        error025: "Error:c025; Debug mode is on but both WorldAddressesDebug and console are not defined, therefore you will not see any debug information. Either include the WorldAddressesDebug file or open your browser's debug console and refresh the current page.",
        error026: "Error:c026; pickerLocation if defined must be a string value containing a field id.",
        error100: "Error:c100; The server failed to respond.",
        error101: "Error:c101; The page you requested could not be found.",
        error102: "Error:c102; There was an internal server error.",
        error103: "Error:c103; The service didn't respond. Please check your settings are correct.",
        error104: "Error:c104; There was a problem with the request.",
        error105: "Error:c105; There was an unknown problem.",
        error106: "Error:c106; Could not download JavaScript. Abort."
    }
};